#Enable EJS script downloads from npm
--remote-components ejs:npm

#Deno js runtime path
--js-runtimes deno:'C:\Users\Shaarav\.deno\bin\deno.exe'

#filename (title - channel) format
-o '%(title)s - %(channel)s'

#Use cookies from Firefox browser mainly for age-restricted videos
--cookies-from-browser 'firefox'

#Set ffmpeg location mainly for converting formats or merging for videos
--ffmpeg-location 'C:\ffmpeg'

#Command
# yt-dlp -P [Path to download] [URL]

# Convert video to audio-only and convert output to mp3
# -x --audio-format 'mp3'  
